### ISSUE TITLE
Multiple Suggest Actions Get Reduced to One

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#6]
Dear authors,

I found another possible bug that makes the execution result different from SMCalFlow. When there are multiple suggestion actions in one turn, OpenDF simply record the first one and discard the rest. See this dialog:

**GUID**: `18863eb5-824a-4f50-adc8-4ade051f8ed5`

 - U1: Add Jacob's soccer game and Kylde park on Monday at 4 p.m. Schedule dinner at Mario's **after the** game at 7.
 - A1: I've put that on your calendar. Your status is set to Busy. I've put that on your calendar. Your status is set to Busy.

OpenDF result:

![Screen Shot 2022-06-17 at 3 40 49 PM](https://user-images.githubusercontent.com/5326890/174391277-5e4aa11a-802c-4604-adb9-35e15268dfb4.png)

You can see the dinner event is not committed. 

I checked the codes and found this line could be the issue:

https://github.com/telepathylabsai/OpenDF/blob/ed8442d112c469a2b08425276b6e83ae7364d133/opendf/graph/dialog_context.py#L138-L140

Although there aren't so many turns that have multiple suggest actions, can we make this `prev_sugg_act` plural to be compatible with SMCalFlow?

**Comment by meron-tl** [comment]
The issue here is that in the current implementation, CreateCommitEventWrapper expects a confirmation before actually committing the suggested event. In this example, a confirmation was not given, so it was not committed.

This is a design decision - do you really want to commit the event without explicit confirmation?

We did play with this idea a bit previously (dialog.py),  allowing to mark one of the suggestion as "implicit agreement" (SUGG_IMPL_AGR), so that if neither RejectSuggestion or AcceptSuggestion are called after a suggestion is made, then that suggestion (marked as implicit agreement) would be applied. But the later implementation (main.py) does not use that, as we didn't have a compelling use case for that.

**Comment by meron-tl** [comment]
Having said that, the lines you pointed out are relevant, together with the way 'do' operates and its evaluation.

We'll look at that again. Thanks!

**Comment by meron-tl** [comment]
It looks like there is some logic in SMCalFlow which decides when to ask for confirmation and when not (so ALWAYS accepting is too aggressive).

It may be something like seeing if the requested DateTime is specific enough, and if it does not clash with other events ?

To be completely consistent with SMCalFlow, first it will be necessary to go over all cases of event creation in the dataset, and verify that the logic to request confirmation agrees with the behaviour in the dataset...

**Comment by hankcs** [comment]
Yes, I agree. Let's leave the logic outside of the core of OpenDF.
