### ISSUE TITLE
opendf.exceptions.python_exception.SemanticException: ConstructError - Unexpected param type - pos2/Str

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#7]
Dear authors,

I spot another bug that nodes like `DayOfWeek(Str(SATURDAY))` won't execute, e.g.:

## Dialog 7

**GUID**: `16aab101-e67c-42a4-887d-d2ad99cc300e` :

 - U1: Put camping trip on my calendar for Saturday at 9 am for 12 hours
 - A1: I've put that on your calendar. Your status is set to Busy.
 - U2: Change that to the Saturday **after that** at 8 am.
 - A2: I've changed your camping trip to February 2nd at 8:00 AM.

Program:

```
 UpdateEvent(
    refer(
       Event?(
          ) ) ,
    AND(
       starts_at(
          nextDayOfWeek(
             :date(
                :start(
                   refer(
                      Event?(
                         ) ) ) ) ,
             DayOfWeek(
                SATURDAY ) ) ) ,
       starts_at(
          NumberAM(
             8 ) ) ) ) 
```

Maybe OpenDF wrongly added a redundant `Str`  to wrap `SATURDAY`?

**Comment by guimaraes-tl** [comment]
Dear hankcs,

The problem here is that `nextDayOfWeek` is expecting a node of type `Str` as second argument.
However, on your expression, a node of type `DayOfWeek` is given.

In this commit [0a4ccfd](https://github.com/telepathylabsai/OpenDF/commit/0a4ccfd3920a377a5581c0a7aa08e32fe9ff3754), I changed it to accept both `Str` and `DayOfWeek`.
Now, both `nextDayOfWeek(..., DayOfWeek(SATURDAY))` and `nextDayOfWeek(..., SATURDAY)` should be fine.

Best regards.
